(() => {
  const games={
    hk4e:{code:'hk4e',label:'原神',biz:'hk4e_',cn:'https://public-operation-hk4e.mihoyo.com',overseas:'https://public-operation-hk4e-sg.hoyoverse.com',pools:[['301','角色活动祈愿',90,true,false,5],['302','武器活动祈愿',80,true,false,5],['500','集录祈愿',90,false,false,5],['2000','千星奇域·活动颂愿',70,false,true,5],['1000','千星奇域·常驻颂愿',70,false,true,4],['200','常驻祈愿',90,false,false,5],['100','新手祈愿',20,false,false,5]]},
    hkrpg:{code:'hkrpg',label:'星穹铁道',biz:'hkrpg_',cn:'https://public-operation-hkrpg.mihoyo.com',overseas:'https://public-operation-hkrpg-sg.hoyoverse.com',pools:[['11','角色活动跃迁',90,true,false,5],['12','光锥活动跃迁',80,true,false,5],['21','角色联动跃迁',90,true,false,5],['22','光锥联动跃迁',80,true,false,5],['1','常驻跃迁',90,false,false,5],['2','新手跃迁',50,false,false,5]]}
  };
  const standard={hk4e:new Set(['琴','迪卢克','莫娜','七七','刻晴','提纳里','迪希雅','梦见月瑞希','阿莫斯之弓','天空之翼','四风原典','天空之卷','狼的末路','天空之傲','和璞鸢','天空之脊','风鹰剑','天空之刃']),hkrpg:new Set(['姬子','瓦尔特','布洛妮娅','杰帕德','克拉拉','白露','彦卿','银河铁道之夜','无可取代的东西','但战斗还未结束','以世界之名','制胜的瞬间','如泥酣眠','时节不居'])};
  const poolType=(game,raw)=>game==='hk4e'&&raw==='400'?'301':game==='hk4e'&&['20011','20012','20021','20022'].includes(raw)?'2000':String(raw||'');
  const compareId=(a,b)=>{const left=String(a).replace(/^0+/,'')||'0',right=String(b).replace(/^0+/,'')||'0';return left.length-right.length||left.localeCompare(right);};
  const order=(a,b)=>String(a.time).localeCompare(String(b.time))||compareId(a.id,b.id);
  const key=account=>`${account.game}:${account.uid}`;
  const recordKey=(game,record,uid=record.uid)=>JSON.stringify([game,String(uid||''),poolType(game,record.uigf_gacha_type||record.gacha_type),String(record.id)]);
  function normalizeDataset(value,game){const root=value||{formatVersion:1,game,accounts:[],records:[],poolSyncState:[]};root.formatVersion=1;root.game=game;root.accounts=root.accounts||[];root.records=(root.records||[]).map(item=>({...item,game,uid:String(item.uid||''),id:String(item.id||'')}));root.poolSyncState=root.poolSyncState||[];return root;}
  function mergeDataset(root,bundles,replace=false){const game=root.game,selected=bundles.filter(bundle=>bundle.account.game===game);if(replace){root.accounts=[];root.records=[];root.poolSyncState=[];}const accounts=new Map(root.accounts.map(item=>[item.uid,item])),records=new Map(root.records.map(item=>[recordKey(game,item),item])),states=new Map(root.poolSyncState.map(item=>[`${item.uid}:${item.poolType}`,item]));let inserted=0,skipped=0;for(const bundle of selected){accounts.set(bundle.account.uid,{...bundle.account,game:undefined});for(const item of bundle.records){const record={...item,game:undefined,uid:item.uid||bundle.account.uid};const identity=recordKey(game,record);if(records.has(identity))skipped++;else{records.set(identity,record);inserted++;}}for(const type of bundle.completedPoolTypes||[])states.set(`${bundle.account.uid}:${type}`,{uid:bundle.account.uid,poolType:type,historyComplete:true});}root.accounts=[...accounts.values()].sort((a,b)=>b.lastSyncAt-a.lastSyncAt);root.records=[...records.values()].sort((a,b)=>-order(a,b));root.poolSyncState=[...states.values()];return{inserted,skipped,accounts:selected.length};}
  function snapshot(game,records,customLossNames=[],sources=['record-field',game==='hk4e'?'paimon-moe':'star-rail-station','local-rules'],accountTimezone=8){const config=games[game],grouped=new Map(),pityByRecord={},observedPermanent=new Set(records.filter(item=>Number(item.rank_type)===5&&poolType(game,item.uigf_gacha_type||item.gacha_type)===(game==='hk4e'?'200':'1')).map(item=>item.name).filter(Boolean));for(const record of records){const type=poolType(game,record.uigf_gacha_type||record.gacha_type);if(!grouped.has(type))grouped.set(type,[]);grouped.get(type).push(record);}const stats=[];for(const raw of config.pools){const [type,label,hardPity,tracksUp,isBeyond,targetRarity]=raw,list=(grouped.get(type)||[]).sort(order);if(!list.length)continue;let pity=0,count3=0,count4=0,count5=0;const targets=[];for(const record of list){pity++;pityByRecord[recordKey(game,record)]=pity;const rarity=Number(record.rank_type)||0;if(rarity===3)count3++;if(rarity===4)count4++;if(rarity===5)count5++;if(rarity===targetRarity){let isLoss=null;if(tracksUp){if(customLossNames.includes(record.name))isLoss=true;const rawUp=String(record.is_up||'').toLowerCase();if(isLoss===null&&sources.includes('record-field')){if(['1','true','up','yes'].includes(rawUp))isLoss=false;else if(['0','false','not_up','not-up','no'].includes(rawUp))isLoss=true;}if(isLoss===null&&window.gachaBannerHistory){const featured=window.gachaBannerHistory.featured(record,game,type,accountTimezone,sources);if(featured!==null)isLoss=!featured;}if(isLoss===null&&sources.includes('local-rules'))isLoss=observedPermanent.has(record.name)||standard[game].has(record.name);}targets.push({record,pity,isLoss});pity=0;}}const upCount=targets.filter(item=>item.isLoss===false).length,lossCount=targets.filter(item=>item.isLoss===true).length;stats.push({type,label,hardPity,tracksUp,isBeyond,targetRarity,total:list.length,count3,count4,count5,currentPity:pity,targetCount:targets.length,averageTargetPity:targets.length?targets.reduce((sum,item)=>sum+item.pity,0)/targets.length:0,upCount,lossCount,averageUpPity:upCount?(list.length-pity)/upCount:0,targetPulls:[...targets].reverse()});}return{records,stats,pityByRecord};}
  function overallLuck(stats){const tracked=stats.filter(item=>item.tracksUp&&item.upCount>0);if(!tracked.length)return'等待第一份 UP 记录';const pulls=tracked.reduce((sum,item)=>sum+item.total-item.currentPity,0),ups=tracked.reduce((sum,item)=>sum+item.upCount,0),hard=tracked.reduce((sum,item)=>sum+item.hardPity*item.upCount,0)/ups,ratio=(pulls/ups)/hard;return ratio<=.55?'天选欧洲人':ratio<=.8?'稳稳的欧洲人':ratio<=1.05?'薛定谔的欧洲人':ratio<=1.35?'非洲旅行者':'大非酋也会转运';}
  function parseLink(input){const cleaned=String(input||'').trim().replace(/\\u0026/gi,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&'),match=cleaned.match(/https?:\/\/[^\s"'<>]+/i);if(!match)throw new Error('没有找到完整的 https 抽卡链接');const raw=match[0].replace(/[)\]},;]+$/,''),url=new URL(raw),params=Object.fromEntries(url.searchParams.entries());if(!params.authkey&&url.hash.includes('?'))Object.assign(params,Object.fromEntries(new URLSearchParams(url.hash.slice(url.hash.indexOf('?')+1))));if(!params.authkey)throw new Error('链接缺少 AuthKey');const lower=raw.toLowerCase(),game=String(params.game_biz||'').startsWith('hkrpg_')||lower.includes('hkrpg')||lower.includes('starrail')?'hkrpg':String(params.game_biz||'').startsWith('hk4e_')||lower.includes('hk4e')||lower.includes('genshin')?'hk4e':null;if(!game)throw new Error('无法判断链接属于原神还是星穹铁道');params.game_biz=params.game_biz||games[game].biz+(lower.includes('hoyoverse')||lower.includes('-sg.')?'global':'cn');params.authkey_ver=params.authkey_ver||'1';params.sign_type=params.sign_type||'2';params.auth_appid=params.auth_appid||'webview_gacha';params.lang=params.lang||'zh-cn';return{game,parameters:params,overseas:lower.includes('hoyoverse')||lower.includes('-sg.')||params.game_biz.endsWith('global')};}
  function requestUrl(link,pool){const config=games[link.game],path=link.game==='hk4e'&&pool[4]?'/gacha_info/api/getBeyondGachaLog':link.game==='hkrpg'&&['21','22'].includes(pool[0])?'/common/gacha_record/api/getLdGachaLog':link.game==='hk4e'?'/gacha_info/api/getGachaLog':'/common/gacha_record/api/getGachaLog',url=new URL((link.overseas?config.overseas:config.cn)+path);for(const [name,value] of Object.entries(link.parameters))if(!['gacha_type','page','size','end_id'].includes(name))url.searchParams.set(name,value);return url;}
  window.gachaModel={games,poolType,order,key,recordKey,normalizeDataset,mergeDataset,snapshot,overallLuck,parseLink,requestUrl};
})();
