import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
globalThis.window=globalThis;
for(const file of ['model','presentation']) (0,eval)(readFileSync(new URL(`../web/${file}.js`,import.meta.url),'utf8'));
const accounts=[{game:'hk4e',uid:'1'},{game:'hkrpg',uid:'2'}],settings={preferences:{}};
assert.equal(gachaPresentation.selection(accounts,accounts[1],settings),accounts[1]);
settings.preferences['selected-account']={type:'string',value:'hkrpg:2'};
assert.equal(gachaPresentation.selection(accounts,null,settings),accounts[1]);
settings.preferences['banner-history-sources:hkrpg:2']={type:'stringSet',value:[]};
settings.preferences['star-rail-loss-names:2']={type:'stringSet',value:['Extra']};
assert.deepEqual(gachaPresentation.analysisOptions(settings,accounts[1]),{sources:[],losses:['Extra']});
assert.ok(gachaPresentation.analysisOptions(settings,accounts[0]).sources.includes('paimon-moe'));
assert.deepEqual(gachaPresentation.analysisOptions(settings,accounts[0]).losses,[]);
const records=Array.from({length:101},(_,i)=>({id:String(i+1),name:'Fixture',time:'2026-09-16 00:00:00',rank_type:'5',gacha_type:'400'}));
const filtered=gachaPresentation.records({records},'hk4e','fixture','301',5);
assert.equal(filtered.length,101);assert.equal(filtered[0].id,'101');assert.equal(records[0].id,'1');
assert.equal(gachaPresentation.records({records},'hk4e','','302',5).length,0);
assert.equal(gachaPresentation.records({records},'hk4e','','all',4).length,0);
assert.equal(gachaPresentation.records({records},'hk4e','2026-09-16','all',5).length,101);
console.log('Gacha presentation: account selection, per-UID settings and record filters OK');
